# Generated by Django 2.2.4 on 2019-08-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('measurement_unit', models.CharField(choices=[('T', 'Ton'), ('Kg', 'Kilograms'), ('g', 'grams'), ('mg', 'milligrams'), ('l', 'Liters'), ('ml', 'milliliters'), ('u', 'Units')], default='u', max_length=2, verbose_name='Measurement Unit')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('can_expire', models.BooleanField(default=False, verbose_name='Can expire ?')),
                ('time_to_expire', models.DurationField(blank=True, verbose_name='Time to expire')),
                ('is_imported', models.BooleanField(default=False, verbose_name='Is imported ?')),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
            },
        ),
    ]
