# Generated by Django 2.2.4 on 2019-09-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('measurement_unit', models.CharField(choices=[('T', 'Toneladas'), ('Kg', 'Kilogramos'), ('g', 'gramos'), ('mg', 'milligramos'), ('l', 'Litros'), ('ml', 'mililitros'), ('u', 'Unidades')], default='u', max_length=2, verbose_name='Unidad de medida')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('can_expire', models.BooleanField(blank=True, default=False, verbose_name='¿Puede expirar?')),
                ('time_to_expire', models.DurationField(blank=True, null=True, verbose_name='Tiempo aproximado en expirar')),
                ('is_imported', models.BooleanField(blank=True, default=False, verbose_name='¿Es importado?')),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
            },
        ),
    ]
