# Generated by Django 2.2.4 on 2019-09-03 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_materials', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='providers',
            field=models.ManyToManyField(through='raw_materials.MaterialProvider', to='raw_materials.Provider', verbose_name='Providers'),
        ),
        migrations.AddField(
            model_name='provider',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='materialprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='raw_materials.Provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='materialprovider',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='raw_materials.RawMaterial', verbose_name='Raw Material'),
        ),
    ]
