# Generated by Django 2.2.5 on 2019-09-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_auto_20190903_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='measurement_unit',
            field=models.CharField(choices=[('T', 'Toneladas'), ('Kg', 'Kilogramos'), ('g', 'gramos'), ('mg', 'milligramos'), ('l', 'Litros'), ('ml', 'mililitros'), ('u', 'Unidades')], default='u', max_length=2, verbose_name='Measurement Unit'),
        ),
    ]
