# Generated by Django 2.2.4 on 2019-09-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0003_auto_20190906_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='can_expire',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Puede expirar?'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='is_imported',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Es importado?'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='measurement_unit',
            field=models.CharField(choices=[('T', 'Toneladas'), ('Kg', 'Kilogramos'), ('g', 'gramos'), ('mg', 'milligramos'), ('l', 'Litros'), ('ml', 'mililitros'), ('u', 'Unidades')], default='u', max_length=2, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='time_to_expire',
            field=models.DurationField(blank=True, verbose_name='Tiempo aproximado en expirar'),
        ),
    ]
