# Generated by Django 2.2.4 on 2019-10-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'Dolares'), ('VEF', 'Bolivares')], max_length=2, null=True, verbose_name='Denominación de la moneda'),
        ),
    ]
