# Generated by Django 2.2.4 on 2019-10-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191008_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'Dolares'), ('VEF', 'Bolivares')], default='VEF', max_length=6, null=True, verbose_name='Denominación de la moneda'),
        ),
    ]
