# Generated by Django 2.2.4 on 2019-09-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DolarPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dollar_price', models.FloatField(verbose_name='Precio del dolar')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSaleRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('cost_dollar', models.FloatField(verbose_name='Costo en Dolares')),
                ('cost_local', models.FloatField(verbose_name='Costo en la moneda local')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('total_cost_dollar', models.FloatField(blank=True, verbose_name='Costo total en dolares')),
                ('total_cost_local', models.FloatField(verbose_name='Costo total en la moneda local')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
