# Generated by Django 2.2.4 on 2019-09-24 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_materials', '0002_auto_20190924_0116'),
        ('sales', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Company'),
        ),
        migrations.AddField(
            model_name='sale',
            name='company_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.CompanyUser'),
        ),
        migrations.AddField(
            model_name='sale',
            name='raw_materials',
            field=models.ManyToManyField(through='sales.MaterialSaleRelation', to='raw_materials.RawMaterial', verbose_name='Materias primas'),
        ),
        migrations.AddField(
            model_name='materialsalerelation',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='raw_materials.Provider', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='materialsalerelation',
            name='raw_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_ocassions', to='raw_materials.RawMaterial', verbose_name='Materia prima'),
        ),
        migrations.AddField(
            model_name='materialsalerelation',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_materials', to='sales.Sale', verbose_name='Venta'),
        ),
    ]
