# Generated by Django 2.2.4 on 2019-09-11 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterField(
            model_name='materialsalerelation',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='materialsalerelation',
            name='cost_dollar',
            field=models.FloatField(verbose_name='Costo en Dolares'),
        ),
        migrations.AlterField(
            model_name='materialsalerelation',
            name='cost_local',
            field=models.FloatField(verbose_name='Costo en la moneda local'),
        ),
        migrations.AlterField(
            model_name='materialsalerelation',
            name='raw_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_ocassions', to='raw_materials.RawMaterial', verbose_name='Materia prima'),
        ),
        migrations.AlterField(
            model_name='materialsalerelation',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_materials', to='sales.Sale', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='raw_materials',
            field=models.ManyToManyField(through='sales.MaterialSaleRelation', to='raw_materials.RawMaterial', verbose_name='Materias primas'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_cost_dollar',
            field=models.FloatField(verbose_name='Costo total en dolares'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_cost_local',
            field=models.FloatField(verbose_name='Costo total en la moneda local'),
        ),
    ]
