# Generated by Django 2.2.4 on 2019-09-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190911_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='DolarPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dollar_price', models.FloatField(verbose_name='Precio del dolar')),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_cost_dollar',
            field=models.FloatField(blank=True, verbose_name='Costo total en dolares'),
        ),
    ]
