# Generated by Django 2.2.4 on 2019-09-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190917_2154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DolarPrices',
            new_name='DolarPrice',
        ),
    ]
